-- wip
ALTER TABLE `toptimizer`.`wip` 
ADD COLUMN `PKG_SIZE` VARCHAR(20) NULL COMMENT '' AFTER `id`,
ADD COLUMN `FLOW` VARCHAR(20) NULL COMMENT '' AFTER `PKG_SIZE`;

-- wip_cut
ALTER TABLE `toptimizer`.`wip_cut` 
ADD COLUMN `PKG_SIZE` VARCHAR(20) NULL COMMENT '' AFTER `id`,
ADD COLUMN `FLOW` VARCHAR(20) NULL COMMENT '' AFTER `PKG_SIZE`;

-- route
ALTER TABLE `toptimizer`.`route` 
ADD COLUMN `PKG_SIZE` VARCHAR(20) NULL COMMENT '' AFTER `id`,
ADD COLUMN `FLOW` VARCHAR(20) NULL COMMENT '' AFTER `PKG_SIZE`;

-- solution
ALTER TABLE `toptimizer`.`solution` 
ADD COLUMN `PKG_SIZE` VARCHAR(20) NULL COMMENT '' AFTER `id`,
ADD COLUMN `FLOW` VARCHAR(20) NULL COMMENT '' AFTER `PKG_SIZE`;
